const fs = require('node:fs');
const path = require('node:path');

const OUTPUT_MARKER = '.academy-build-output';

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function ensureDirectory(directoryPath, label) {
  if (!fs.existsSync(directoryPath) || !fs.statSync(directoryPath).isDirectory()) {
    throw new Error(`${label} does not exist: ${directoryPath}`);
  }
}

function prepareOutput(outDir) {
  if (fs.existsSync(outDir)) {
    const marker = path.join(outDir, OUTPUT_MARKER);
    if (!fs.existsSync(marker) || fs.lstatSync(outDir).isSymbolicLink()) {
      throw new Error(`Refusing to replace unmarked output directory: ${outDir}`);
    }
    fs.rmSync(outDir, { recursive: true });
  }
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, OUTPUT_MARKER), 'Generated by scripts/build-academy.cjs\n');
}

function copyRequired(sourcePath, destinationPath, label) {
  if (!fs.existsSync(sourcePath)) {
    throw new Error(`${label} does not exist: ${sourcePath}`);
  }
  fs.mkdirSync(path.dirname(destinationPath), { recursive: true });
  fs.cpSync(sourcePath, destinationPath, { recursive: true, force: true });
}

function walkFiles(root, extension) {
  const files = [];
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    const absolutePath = path.join(root, entry.name);
    if (entry.isDirectory()) files.push(...walkFiles(absolutePath, extension));
    else if (!extension || path.extname(entry.name).toLowerCase() === extension) files.push(absolutePath);
  }
  return files;
}

function canonicalUrl(base, relativePath) {
  const normalized = relativePath.split(path.sep).join('/');
  if (normalized === 'index.html') return base;
  if (normalized.endsWith('/index.html')) return new URL(normalized.slice(0, -10), base).href;
  return new URL(normalized, base).href;
}

function normalizeHtml(targetRoot, course) {
  for (const htmlPath of walkFiles(targetRoot, '.html')) {
    const relativePath = path.relative(targetRoot, htmlPath);
    let html = fs.readFileSync(htmlPath, 'utf8');
    for (const rewrite of course.rewrites || []) {
      html = html.split(rewrite.from).join(rewrite.to);
    }
    html = html.replace(/\s*<link\b[^>]*rel=["']canonical["'][^>]*>/gi, '');
    const canonical = `<link rel="canonical" href="${canonicalUrl(course.canonicalBase, relativePath)}">`;
    if (!/<\/head>/i.test(html)) throw new Error(`HTML has no </head>: ${htmlPath}`);
    html = html.replace(/<\/head>/i, `${canonical}\n</head>`);
    fs.writeFileSync(htmlPath, html);
  }
}

function localReferences(html) {
  const references = [];
  const attributePattern = /<(?:a|img|iframe|link|script|source)\b[^>]*\b(?:href|src)=["']([^"']+)["']/gi;
  for (const match of html.matchAll(attributePattern)) references.push(match[1]);
  return references;
}

function isExternal(reference) {
  return /^(?:[a-z]+:|\/\/|#)/i.test(reference) || reference.includes('+') || reference.includes('{');
}

function resolveLocalReference(outDir, ownerPath, reference) {
  const cleanReference = reference.split('#')[0].split('?')[0];
  if (!cleanReference) return null;
  const decodedReference = decodeURIComponent(cleanReference);
  let targetPath = decodedReference.startsWith('/')
    ? path.join(outDir, decodedReference.replace(/^[/\\]+/, ''))
    : path.resolve(path.dirname(ownerPath), decodedReference);
  if (decodedReference.endsWith('/')) targetPath = path.join(targetPath, 'index.html');
  else if (fs.existsSync(targetPath) && fs.statSync(targetPath).isDirectory()) targetPath = path.join(targetPath, 'index.html');
  return targetPath;
}

function jsonReferences(value, references = []) {
  if (Array.isArray(value)) {
    for (const item of value) jsonReferences(item, references);
  } else if (value && typeof value === 'object') {
    for (const [key, item] of Object.entries(value)) {
      if ((key === 'deck' || key === 'url') && typeof item === 'string') references.push(item);
      else jsonReferences(item, references);
    }
  }
  return references;
}

function validateArtifact(outDir, legacyHostname) {
  const htmlFiles = walkFiles(outDir, '.html');
  for (const htmlPath of htmlFiles) {
    const html = fs.readFileSync(htmlPath, 'utf8');
    const legacyLink = new RegExp(`(?:href|src)=["']https?:\\/\\/${legacyHostname.replace(/\./g, '\\.')}`, 'i');
    if (legacyLink.test(html)) throw new Error(`Legacy hostname found in generated navigation: ${htmlPath}`);

    for (const reference of localReferences(html)) {
      if (!reference || isExternal(reference)) continue;
      const targetPath = resolveLocalReference(outDir, htmlPath, reference);
      if (!targetPath) continue;
      if (!fs.existsSync(targetPath)) {
        throw new Error(`Missing local asset referenced by ${path.relative(outDir, htmlPath)}: ${reference}`);
      }
    }
  }

  for (const jsonPath of walkFiles(outDir, '.json')) {
    const document = readJson(jsonPath);
    for (const reference of jsonReferences(document)) {
      if (!reference || isExternal(reference)) continue;
      const targetPath = resolveLocalReference(outDir, jsonPath, reference);
      if (targetPath && !fs.existsSync(targetPath)) {
        throw new Error(`Missing local file referenced by ${path.relative(outDir, jsonPath)}: ${reference}`);
      }
    }
  }
  return htmlFiles.length;
}

function validateManifest(manifest) {
  if (manifest.schemaVersion !== 1) throw new Error(`Unsupported manifest schema: ${manifest.schemaVersion}`);
  if (!manifest.courses || typeof manifest.courses !== 'object') throw new Error('Manifest must declare courses');
  for (const [courseId, course] of Object.entries(manifest.courses)) {
    if (!course.sourcePath || !course.publicPath || !course.canonicalBase) {
      throw new Error(`Incomplete course declaration ${courseId}: ${JSON.stringify(course)}`);
    }
  }
}

function buildAcademy(options) {
  const academyRoot = path.resolve(options.academyRoot);
  const outDir = path.resolve(options.outDir);
  const manifestPath = path.resolve(options.manifestPath || path.join(academyRoot, 'academy.courses.json'));
  const manifest = readJson(manifestPath);
  validateManifest(manifest);
  ensureDirectory(academyRoot, 'Academy root');
  prepareOutput(outDir);

  copyRequired(path.join(academyRoot, 'index.html'), path.join(outDir, 'index.html'), 'Academy index');
  copyRequired(path.join(academyRoot, 'CNAME'), path.join(outDir, 'CNAME'), 'Academy CNAME');
  copyRequired(path.join(academyRoot, 'assets'), path.join(outDir, 'assets'), 'Academy assets');

  for (const [courseId, course] of Object.entries(manifest.courses)) {
    const courseRoot = path.join(academyRoot, course.sourcePath);
    ensureDirectory(courseRoot, `Course root ${courseId}`);
    for (const shared of course.sharedPublishes || []) {
      copyRequired(
        path.join(courseRoot, shared.sourcePath),
        path.join(outDir, shared.publicPath),
        `Shared publish ${courseId}:${shared.sourcePath}`
      );
    }
    const targetRoot = path.join(outDir, course.publicPath);
    copyRequired(courseRoot, targetRoot, `Course ${courseId}`);
    for (const shared of course.sharedPublishes || []) {
      fs.rmSync(path.join(targetRoot, shared.sourcePath.split('/')[0]), { recursive: true, force: true });
    }
    normalizeHtml(targetRoot, course);
  }

  const htmlFiles = validateArtifact(outDir, manifest.legacyHostname);
  return { hubs: Object.keys(manifest.courses).length, htmlFiles, outDir };
}

function option(args, name, fallback) {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] : fallback;
}

if (require.main === module) {
  const args = process.argv.slice(2);
  const academyRoot = path.resolve(__dirname, '..');
  const manifestPath = option(args, '--manifest', path.join(academyRoot, 'academy.courses.json'));
  const result = buildAcademy({
    academyRoot,
    outDir: option(args, '--out', path.join(academyRoot, '_site')),
    manifestPath
  });
  console.log(`Academy build complete: ${result.hubs} hubs, ${result.htmlFiles} HTML files, ${result.outDir}`);
}

module.exports = { buildAcademy };
